import matplotlib.pyplot as plt
import numpy as np
data = np.loadtxt("vals.txt")
#print(data)
y1 = np.array(data[0])
y2 = np.array(data[1])
x = np.arange(-25, 26)
plt.xlim(-25,25)
plt.ylim(0, 50)
plt.stem(x, y1,markerfmt='o')
#plt.title("Plotting x(n)")
plt.xlabel("n")
plt.ylabel("x(n)")
plt.xticks(np.arange(-25, 26, 5))
plt.yticks(np.arange(0, 50, 5))
plt.grid(True)
plt.savefig("graph1.png")
plt.show()
plt.clf()
plt.xlim(-25,25)
plt.ylim(-25,25)
plt.stem(x, y2,markerfmt='o')
#plt.title("Plotting x(n)")
plt.xlabel("n")
plt.ylabel("x(n)")
plt.xticks(np.arange(-25, 26, 5))
plt.yticks(np.arange(-25,26, 5))
plt.grid(True)
plt.savefig("graph2.png")
plt.show()
